### ISSUE TITLE
[Feature Request] Add JIRA project key whitelist

### ISSUE THREAD

**Issue by kenime** [Gherciu/commitlint-jira#17]
Seems there is no rule to check JIRA project key, it would be nice to add something like

jira-task-id-project-key: 'project-key' | ['project-key1', 'project-key2']

**Comment by Gherciu** [comment]
@kenime This feature will be part of commitlint-config-jira@v1.4.0 and commitlint-plugin-jira-rules@v1.4.0

**Comment by Gherciu** [comment]
@kenime v1.4.0 has been published ) Thanks again
