### ISSUE TITLE
turning off jira-commit-message-separator causes an exception

### ISSUE THREAD

**Issue by Lagily** [Gherciu/commitlint-jira#26]
While trying to turn off the "jira-commit-message-separator" rule based on the example in the README, I receive an exception.

```
module.exports = {
  plugins: ["commitlint-plugin-jira-rules"],
  extends: ["jira"],
  rules: {
    "jira-commit-message-separator": 0,
  },
};
```

**frontend\node_modules\@commitlint\cli\lib\cli.js:124
	throw err;
	^

Error: config for rule jira-commit-message-separator must be array, received 0 of type number
    at Object.<anonymous> (frontend\node_modules\@commitlint\lint\lib\index.js:119:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)**

Suggestion: Add an example for disabling the rule in the README.

**Comment by AlexeiCrr** [comment]
Is this issue fixed? How can i address it?

**Comment by norbertsuskiyoti** [comment]
You should use `"jira-commit-message-separator": [0]`, but this one seems to be ignored totally..

**Comment by Gherciu** [comment]
@AlexeiCrr @Lagily @norbertsuskiyoti    at the moment this rule  is ignored cause commitlint-cli in new versions doesn't provide enough tools to implement this rule....sorry guys.....I'll update the docs to not confuse people or i'll try another time to find a workaround....but PR's also are welcome if someone know how to make it working)
