### ISSUE TITLE
Using Jira Ticket with type

### ISSUE THREAD

**Issue by cristianjesuszup** [Gherciu/commitlint-jira#28]
Hello! I need create this template on commitlint: [XXX-123] type: subject
what rules can i put in order to reach this standard?

**Comment by Gherciu** [comment]
@cristianjesuszup  see this https://github.com/Gherciu/commitlint-jira/issues/33

**Comment by giovai** [comment]
Hello! The example in #33 shows only the `jira-task-id-project-key` rule, without the `type-enum`. Could you explain if it's possible to enforce the following: 
type: taskId: subject
example: fix: PROJ-123: my commit
