### ISSUE TITLE
Using commitlint-jira with git-cz 

### ISSUE THREAD

**Issue by yaldram** [Gherciu/commitlint-jira#29]
Hello thanks a lot for this awesome package. I am using git-cz for some meaningful commits with some neat emojis but also want to attach JIRA tickets inside the Commits. So my Commit format would be - 

```🎸 feat: PP-64: Added Linting to the Project.```

But when I followed the README I get various errors like `jira-task-id-case`, `jira-commit-status-case`, `jira-task-id-separator`. I tried a number of combinations by adding and removing rules but no luck.

@Gherciu, Sir please can you help me with the setup if I were to achieve the above commit message format. Thanks

**Comment by Gherciu** [comment]
Hi @yaldram  unfortunately, at the moment it's not possible to  use 2 different git commit styles pls choose one or (Jira style or default commitlint style)  ...in your case I think will be a good idea to choose the default commitlint style ex: (🎸 feat(PP-66): my commit)
