### ISSUE TITLE
Setting jira-task-id-project-key Rule

### ISSUE THREAD

**Issue by wasitim** [Gherciu/commitlint-jira#33]
In commitlint.config.js, I'm trying to set the task id project key to enforce using **UP**. I've tried:

module.exports = {
    plugins: ['commitlint-plugin-jira-rules'],
    extends: ['jira'],
    rules: {
        'jira-task-id-project-key': ['UP'],
    }
}

**and** 

module.exports = {
    plugins: ['commitlint-plugin-jira-rules'],
    extends: ['jira'],
    rules: {
        'jira-task-id-project-key': 'UP',
    }
}

**In package.json I have:**

"husky": {
    "hooks": { 
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-push": "npm run test:ci"
    }
  }

**Running git commit -m 'UP-1: hey'**

**I get:**

tim2020mbp:scripts tim$ git commit -m 'UP-1: hey'
husky > commit-msg (node v14.5.0)
/Users/tim/projects/ae/ae-up-ui/node_modules/@commitlint/cli/lib/cli.js:131
  throw err;
  ^

Error: level for rule jira-task-id-project-key must be number, received 'UP' of type string
    at lint (/Users/tim/projects/ae/ae-up-ui/node_modules/@commitlint/lint/lib/lint.js:84:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
husky > commit-msg hook failed (add --no-verify to bypass)

LIbs in package.json
    "@commitlint/cli": "^9.1.1",
    "commitlint-config-jira": "^1.4.1",
    "commitlint-plugin-jira-rules": "^1.4.0",

**Comment by flinders-corey** [comment]
Hi @wasitim 

I had this issue as well today. I resolved it by configuring the `jira-task-id-project-key` rule like this:

```javascript
"rules": {
  "jira-task-id-project-key": [
    2, "always", "BOTS"
  ]
}
```

My understanding is that the config needs to be in form of a three element array:

- level: If a rule failure is a warning or an error
- applicable: when is the rule should be applied
- value: the value to use for the rule

So in your example the config would be something like:

```javascript
"rules": {
  "jira-task-id-project-key": [
    2, "always", "UP"
  ]
}
```
More information on the way commitlint configures rules is [available here][rules]


[rules]: https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md
