### ISSUE TITLE
Custom jira-task-id

### ISSUE THREAD

**Issue by JeremieLapert** [Gherciu/commitlint-jira#39]
Hello,
After reading the documentation and testing several solutions, i need hello.
My objectif is to obtain this valid commit :
`[DM-189] :  commit text`

Do you have any idea how to achieve this result?

Thank you in advance for your answers and your help.

Jérémie

**Comment by workkk98** [comment]
commitlint plugins may help you.

**Comment by JeremieLapert** [comment]
Thank you for your answer ! do you have any examples or leads?

**Comment by Gherciu** [comment]
@JeremieLapert  why do you need brackets `[  ]`  ?? this plugin is designed to write less chars....but if you need to achieve this format consider using the conventional comitlint-cli plugin https://github.com/conventional-changelog/commitlint#getting-started
