### ISSUE TITLE
not able to run local test

### ISSUE THREAD

**Issue by Jagatmachines** [Gherciu/commitlint-jira#5]
![Screenshot 2019-10-11 20:49:26](https://user-images.githubusercontent.com/33274614/66662570-cb1dea00-ec68-11e9-881f-7079ff540c95.png)

while running the local test for rules in commitlint-jira-e2e-tests facing issues

Procedure followed:
npm run watch:packages
cd packages/commitlint-jira-e2e-tests
echo hello | commitlint
<Error occured as shown in screenshot>

**Comment by Gherciu** [comment]
pls run these commands in this sequence in the root folder (/commitlint-jira):
1. npm i - to install root dependencies
2. npm run link:packages - to install all dependencies in all packages
3. npm run build:packages - to bundle/build all packages

If you want to run unit tests for all packages run `npm run test:packages`
If you want to run e2e tests change the directory `cd packages/commitlint-jira-e2e-tests` , 
then run `npx jest` to start e2e tests or if you want to test locally in the console run
 `echo "IB-21: my commit message" | npx commitlint`
