### ISSUE TITLE
Task ID must be provided.

### ISSUE THREAD

**Issue by toondaey** [Gherciu/commitlint-jira#6]
Want to say a big thank you for this plugin.
So I just started using this package today, however, I've been getting this issue for a commit message of this format.
```
[TRANSITION]COMP-83: my commit message
```
What do I do?

**Comment by Gherciu** [comment]
@toondaey  can you pls provide the error output

**Comment by toondaey** [comment]
@Gherciu 
⧗   input: [STARTED]CCHUB-83: filter for submissions by status
✖   the commit message must provide minimum one task id followed by (:) symbol, if task not have an id use a conventional task id e.g: "IB-0000: My commit message" [jira-task-id-empty]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)

**Comment by toondaey** [comment]
@Gherciu 
⧗   input: [TRANSITION]COMP-83: my commit message
✖   the commit message must provide minimum one task id followed by (:) symbol, if task not have an id use a conventional task id e.g: "IB-0000: My commit message" [jira-task-id-empty]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)

**Comment by Gherciu** [comment]
@toondaey  can you pls provide the  version what you use

**Comment by toondaey** [comment]
v1.1.0

**Comment by Gherciu** [comment]
@toondaey  pls provide the full console output and `commitlint.config.js` file.

**Comment by toondaey** [comment]
`commitlint.config.js`
```
module.exports = {
    plugins: ['commitlint-plugin-jira-rules'],
    extends: ['jira',]
};
```
console output is:
```
husky > commit-msg (node v10.16.3)
⧗   input: [TRANSITION]COMP-83: my commit message
✖   the commit message must provide minimum one task id followed by (:) symbol, if task not have an id use a conventional task id e.g: "IB-0000: My commit message" [jira-task-id-empty]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)
```

However, I'm using `git commit -a` (which opens the vim git editor) to commit my files.

**Comment by Gherciu** [comment]
@toondaey pls follow these steps.
`git add .` to stage all files
`git commit -m"[TRANSITION]COMP-83: my message"`
I think is a problem with -a flag. I promise to resolve this later

**Comment by toondaey** [comment]
@Gherciu Thanks.
I just tried with the `-m` flag and it worked. I guess it has to do with the flag after.
Just wanted to say a big thank you for the plugin though. It has really made things easier for me.

**Comment by Gherciu** [comment]
@toondaey Thanks for open this issue. In the next release, I will investigate this issue and resolve. Until next release use pls `-m` flag.

**Comment by Gherciu** [comment]
@toondaey Pls update all commit-lint-jira packages to last versions. This issue is now fixed:
- commitlint-config-jira: 1.1.0 => 1.2.0
- commitlint-plugin-jira-rules: 1.1.0 => 1.2.0
Just run in terminal `npm i commitlint-config-jira@1.2.0 commitlint-plugin-jira-rules@1.2.0`

**Comment by toondaey** [comment]
Thanks @Gherciu
