### ISSUE TITLE
'jira-task-id-empty' is being emitted when the commit message contains URLs

### ISSUE THREAD

**Issue by JoaoVictorLouro** [Gherciu/commitlint-jira#7]
'jira-task-id-empty' is being emitted when there is a URL inside the commit message.
here is a sample commit message:

TEST-1: #done #time 10h Testing commitlint
https://mytracker.atlassian.net/browse/TEST-1
#comment Testing if it works or not

this will break into the commit message into 3 task ids:
1: "TEST-1" -> CORRECT
2: "#done #time 10h Testing commitlint↵https" -> SHOULDN'T EXIST
3: "//mytracker.atlassian.net/browse/TEST-1↵#comment Testing if it works or not" -> SHOULDN'T EXIST

I propose adding this regex to the filter function: `taskId.search(/[A-Z]+-[0-9]+/) == 0`, it should fix the issue.

**Comment by Gherciu** [comment]
@JoaoVictorLouro Pls update all commit-lint-jira packages to last versions:
- commitlint-config-jira: 1.1.0 => 1.2.0
- commitlint-plugin-jira-rules: 1.1.0 => 1.2.0
Just run in terminal `npm i commitlint-config-jira@1.2.0 commitlint-plugin-jira-rules@1.2.0`
